# Site Settings
title: My Resume
url: 'http://kylephp.github.io/'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Kyle Hoang
tagline: Senior PHP Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<strong>Facts about me:</strong>
<ul><li>I am a full stack developer with a hungry and open mind.</li>
<li>I love to use and contribute to open source systems.</li>
<li>I cannot develop anything without using Git.</li>
<li>I use Linux, mainly Ubuntu. I can use other systems but you do not want me to do so.</li>
<li>I learn how to get work-life balance.</li>'

#sidebar links
email: kylephp.dev@gmail.com
phone: +84 902 554 255
website: kylephp.github.io #do not add http://
github: kylephp
twitter: '@kylephp'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111887737-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
